name: Build Docker image

on:
   push:  
    branches:
      - main
      - master   
jobs:
  docker:
    name: main
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGION: ${{ secrets.REGION }}

      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
   
    steps:    
      -
        name: Get commit ID
        id: commit
        uses: prompt/actions-commit-hash@v3
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./docker/Dockerfile
          push: true
          tags: dockerprojectuser/inbound_rules_scaner:${{ steps.commit.outputs.short }}