name: Run inbound rules scanner in Docker Container

on:
   schedule:
     - cron: '*/2 * * * *'

jobs:
  build-and-run:
    name: main
    runs-on: ubuntu-latest
    
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGION: ${{ secrets.REGION }}

      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      -
          uses: actions/checkout@v2
          with:
            ref: ${{ github.event.pull_request.head.sha }}
      -
          name: Get the last commit hash of master
          run: |
            echo ${{ github.event.pull_request.head.sha }}
            last_commit= git rev-parse --short HEAD
            $last_commit
            
      -
        name: Run Docker container
        run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
          docker pull dockerprojectuser/inbound_rules_scaner:$(git rev-parse --short HEAD)
          docker run --rm -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e S3_BUCKET_NAME -e REGION dockerprojectuser/inbound_rules_scaner:$(git rev-parse --short HEAD) --dry-run
