name: Run inbound rules scanner in Docker Container

on:
   schedule:
       - cron: '*/2 * * * *'

jobs:
  build-and-run:
    name: main
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGION: ${{ secrets.REGION }}

      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      -
          uses: actions/checkout@v2
      -
          name: Get the last commit hash of master
          run: |
            git fetch --depth=1 origin main
            echo "The last commit hash in master is $(git rev-parse --short HEAD)"
            conn=$(git rev-parse --short HEAD)
            echo $conn
      -
        name: Run Docker container
        run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
          
          docker run --name inbound_rule_scanner -d -it -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e S3_BUCKET_NAME -e REGION dockerprojectuser/inbound_rules_scaner:$(git rev-parse --short HEAD) /bin/bash --dry-run
          docker exec inbound_rule_scanner sh -c "python scanner/in_scanner.py"  
